"use client";
import "./globals.css";
import React from "react";
import { Geist, Geist_Mono } from "next/font/google";
import { Provider } from "react-redux";
import { store } from "../redux/store/store";
import { Sidebar } from "./components/sidebar";
import Cookies from "js-cookie";
import { useRouter } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const router = useRouter();

  React.useEffect(() => {
    // Get a cookie
    const user = Cookies.get("USER_TOKEN");

    if (!user) {
      router.push("/login");
    }

    console.log("User:", user);
  }, []);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider store={store}>
          <Sidebar>{children}</Sidebar>
        </Provider>
      </body>
    </html>
  );
}
